language: c

before_install:
    - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake

script:
    - cmake .
    - make
    - ./frontends/test/bin/tests

notifications:
    email:
        - sir@cmpwn.com
    irc:
        channels:
            - "chat.freenode.net#knightos"
        on_success: change
        on_failure: always
        skip_join: true
